name: Workflow for Deploy Blog Server to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: CI=false npm run build
      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: "${{ secrets.TARGET_DIR }}"
          remote_host: "${{ secrets.HOST_DNS }}"
          remote_user: "${{ secrets.USERNAME }}"
          remote_key:  "${{ secrets.EC2_SSH_KEY }}"