name: Workflow to deploy blog server to EC2 instance
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY  }}
          HOSTNAME : ${{ secrets.HOST_DNS  }}
          USER_NAME : ${{ secrets.USERNAME  }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            DIR="/home/ubuntu/projects/blogger"
            pm2 delete all
            cd /home/ubuntu/projects
            if [ ! -d $DIR ]
            then
              mkdir blogger &&
              git clone https://github.com/ShiedaKayn1975/BloggerServer.git blogger &&
              cd blogger &&
              npm i
            else
              cd blogger
            fi

            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            sudo pm2 start server.js
          '